import { Poppins } from "next/font/google";
import "./globals.css";
import { NavBar } from "./components/navbar/NavBar";
import { Footer } from './components/footer/Footer';

const poppins = Poppins({ subsets: ["latin"], weight: "500" });

export const metadata = {
  title: "LA BARRA SPORT & BAR",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
