import './globals.css';
import { Footer } from './components/footer/Footer';
import { NavBar } from "./components/navbar/NavBar";
import { ClerkProvider } from "@clerk/nextjs";
import { Poppins } from "next/font/google";
import { usePathname } from 'next/navigation';

const poppins = Poppins({ subsets: ["latin"], weight: "500" });

export const metadata = {
  title: "La barra sport & bar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={poppins.className}>
          <NavBar />
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
